### ISSUE TITLE
Create API for automated adding of calendars

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#1]
CSV files can be maintained as logging, but we should be able to push calendars directly from the spider. Calendars should remain inactive until they're reviewed.

**Comment by flowersjg** [comment]
Before a calendar is added, it should pass through a pipeline which:
- [ ] labels it with the appropriate school_year_id
- [ ] removes special characters per #7 
- [ ] standardizes Google Calendar urls

These are candidates for the utility app from #5.

**Comment by johnnyflowers** [comment]
#57 depends on this.
