### ISSUE TITLE
Find a better way to assign a calendar to a school rather than a district

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#11]
When editing calendars via spreadsheet, the auditor should be able to specify an owning school via a column such as school_id (cumbersome for the user) or school_calendars_url (maybe not foolproof if the link used is for a specific calendar on the school's page, but this can be accounted for in the code that imports the updated data).

**Comment by johnnyflowers** [comment]
#57 will have to solve this.
