### ISSUE TITLE
Investigate using Whitenose for serving static files

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#25]
See:
https://devcenter.heroku.com/articles/django-assets
http://jamie.curle.io/blog/static-assets-django-heroku/
https://pypi.python.org/pypi/whitenoise

**Comment by johnnyflowers** [comment]
Whitenoise can't be used because it traverses all static files whenever the wsgi app starts (adding a URL for each to memory), which is prohibitively slow for our enormous number of static files.
