### ISSUE TITLE
Spider should insert calendars for audit directly into production database

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#28]
The necessary table structure differs enough from audited calendars that a separate table is justified. This has been done ad hoc for a while, but there's no reason that we shouldn't use the same staging table repeatedly. This will just require marking what state a calendar is in (recently imported vs audited and ready to move to the real table).

**Comment by flowersjg** [comment]
I'll wait to do this until after the current round of auditing is done so that the table can start from scratch in a known state.

**Comment by flowersjg** [comment]
Additionally, a script should be written which:
[ ] - Makes an empty, temporary copy of the staging table
[ ] - Imports audited calendars from CSV into the temp table
[ ] - Takes calendars from the temp table marked as belonging to a school, updates them appropriately in the staging table (name, school_id, school_year_id, calendar_uri, calendar_source_uri, and audited status), and removes them from the temp table
[ ] - Moves the same data for district calendars from the temp table to the staging table
[ ] - Produces a warning if rows remain in the temp table, or else drops the temp table
[ ] - Copies all audited calendars into the production table

**Comment by johnnyflowers** [comment]
Having figured out that I can have our spider on EC2 connect directly to our database server on Heroku, this process can be simplified a bit. Many of the elements on the checklist above can probably be eliminated, but I'll evaluate this in conjunction with work on #57.
