### ISSUE TITLE
Explore the idea of auditing calendars in the site admin

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#3]
Performance will be a consideration (slow queries through the ORM), as will be the necessary amount of navigation.

Alternative to #4.

**Comment by johnnyflowers** [comment]
This is basically being superseded by #57. I'll keep it around in case I think of a reason to use the builtin django admin interface for something.

**Comment by johnnyflowers** [comment]
Rolling our own.
