### ISSUE TITLE
New school to add - Wake County Public Schools

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#31]
http://www.wcpss.net/Page/330

Richland Creek Elementary School
840 Wallridge Road
Wake Forest NC 27587
919-554-6333

Our district URL: http://www.schoolcalendars.org/north-carolina/wake-county-public-school-system-921258/schools/

**Comment by johnnyflowers** [comment]
Not sure when this happened, but this school has been added.
