### ISSUE TITLE
Google calendar URLs should be formatted consistently

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#32]
We need to be sure that for every google calendar we host, the URL is constructed to include:

?showTitle=1&showNav=1&showDate=1 

in the actual URL itself. Otherwise, users will not be able to browse into future months.

This is likely something you already did last year, but we have no way of knowing because of the lack of git, heh.

**Comment by johnnyflowers** [comment]
Marking as high priority so that I make extra sure that this finds a permanent home somewhere. I know it's part of at least a couple of scripts, but I don't want it to get lost as I canonize the process.
