### ISSUE TITLE
San Diego Unified

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#35]
We need to add a reminder to our personal calendars to double check the 2016-2017 calendars for San Diego Unified district, because there is a proposal to change their start date. I don't think it has been decided yet.

http://www.sandi.net/Page/71863

Their official calendar page: http://www.sandi.net/site/Default.aspx?PageID=2400

This has no bearing on our existing data as I have audited in return of calendar names.

**Comment by johnnyflowers** [comment]
Well, I guess we put this one off long enough!
