### ISSUE TITLE
Write utility scripts for csv output and input

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#4]
This is currently done ad hoc and is annoying.

- [x] import CSV from spider output into a temporary database table
- [x] export to CSV for auditing
- [ ] import audited CSV into aforementioned temporary database table
 - [ ] move audited calendars into main calendars table
 - [ ] drop temporary table
 - [ ] re-score calendars

**Comment by flowersjg** [comment]
- [ ] import CSV from spider output into a temporary database table
- [ ] export to CSV for auditing
- [ ] import audited CSV into aforementioned temporary database table
 - [ ] move audited calendars into main calendars table
 - [ ] drop temporary table

**Comment by johnnyflowers** [comment]
I really hope I can make all of this go away with #57.
