### ISSUE TITLE
Most popular districts needing to be added.

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#46]
Should we go ahead and redirect our 14/15 calendars to 15/16 when we have them up? 

Davidson/Nashville
new calendar: http://www.mnps.org/dynimg/_HMAAA_/docid/0x7AC106AB33127074/10/2015-16_District_Calendar.pdf

Cincinnati Public Schools
new calendar:  http://www.cps-k12.org/sites/www.cps-k12.org/files/pdfs/2015-16-DistrictCalendarREV4-2-6-15.pdf

Bullitt County School District - Kentucky (old calendar: http://www.schoolcalendars.org/kentucky/bullitt-county-school-district-918221/calendar-18668/ )
new calendar: http://www.bullittschools.org.schools.bz/docs//userfiles/19/my%20files/calendars/15-16%20parent%20calendar%20approved.pdf?id=545855

**Comment by johnnyflowers** [comment]
These districts have calendars for 2017 - 2018.
