### ISSUE TITLE
Fairfield City School District

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#51]
They have PDFs on two pages. We need to merge to one for each year.

21755   http://www.fairfieldcityschools.com/ourpages/auto/2013/1/11/59367615/2017-18 School Calendar page 1.pdf http://www.fairfieldcityschools.com/apps/pages/index.jsp?uREC_ID=205274&type=d  2017 - 2018 School Calendar page 1.pdf  2017 - 2018 Fairfield City School District  
21754   http://www.fairfieldcityschools.com/ourpages/auto/2013/1/11/59367615/2016-17 School Calendar page 1.pdf http://www.fairfieldcityschools.com/apps/pages/index.jsp?uREC_ID=205274&type=d  2016 - 2017 School Calendar page 1.pdf  2016 - 2017 Fairfield City School District  
21752   http://www.fairfieldcityschools.com/ourpages/auto/2013/1/11/59367615/2015-16 School Calendar Page 01.pdf    http://www.fairfieldcityschools.com/apps/pages/index.jsp?uREC_ID=205274&type=d  2015 - 2016 School Calendar Page 01.pdf 2015 - 2016 Fairfield City School District  
21753   http://www.fairfieldcityschools.com/ourpages/auto/2013/1/11/59367615/2015-16 School Calendar Page 02.pdf    http://www.fairfieldcityschools.com/apps/pages/index.jsp?uREC_ID=205274&type=d  2015 - 2016 School Calendar Page 02.pdf 2015 - 2016 Fairfield City School District  
21751   http://www.fairfieldcityschools.com/ourpages/auto/2013/1/11/59367615/2014-15 School District Calendar.pdf   http://www.fairfieldcityschools.com/apps/pages/index.jsp?uREC_ID=205274&type=d  2014-15 School District Calendar.pdf    0   Fairfield City School District

**Comment by johnnyflowers** [comment]
Looking good these days.
