### ISSUE TITLE
Redwood City School District

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#52]
Our page: http://www.schoolcalendars.org/california/redwood-city-school-district-915404/

They have this page:

http://www.rcsd.k12.ca.us/site/default.aspx?PageType=3&DomainID=1&ModuleInstanceID=1524&ViewID=047E6BE3-6D87-4130-8424-D8E4E9ED6C2A&RenderLoc=0&FlexDataID=7259&PageID=1

It's all text. We'll need to copy it into a PDF and display that I guess. They also have an ical that I have imported. The URL is here:  https://www.google.com/calendar/embed?src=vkplieilt06219rro77qkctlmom6860t%40import.calendar.google.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"

The existing "Hoover" google calendar, we can take down and replace with the one above.

**Comment by johnnyflowers** [comment]
Updated: http://www.schoolcalendars.org/california/redwood-city-school-district-915404/calendar-28448/
