### ISSUE TITLE
done_calendars_staging_20150717

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#54]
For Alpine School District - Their calendars for individual schools.I think I got all of their duplicates marked with a 0 for the year, but it is possible I missed a few. You may want to make certain there are no duplicate URLs in school_calendars_school_url when you go to integrate.

Also, are you not pushing any 2014-15 calendars to production from the return of school names?  I would not do it, because if the spider has called them 14-15, I'm not really looking at them.

**Comment by johnnyflowers** [comment]
I'm going to go ahead and close issues that deal with past audits in favor of the upcoming school year. We'll get an auditing interface in place per #57.
