### ISSUE TITLE
Automate generation of watermarked calendar jpgs after audit

### ISSUE THREAD

**Issue by flowersjg** [johnnyflowers/schoolcalendars#8]
This should happen automatically after either #3 or #4 finishes. This does, however, require that image generation happen on the EC2 instance rather than on a dev machine. Failing to connect to the EC2 instance should be handled gracefully and usefully.

**Comment by flowersjg** [comment]
This script would additionally need to be able to mark its success or failure and update image storage locations in the database via the API from #1.

**Comment by johnnyflowers** [comment]
#57 needs to take care of this.

**Comment by johnnyflowers** [comment]
This also needs to push the images to S3, and then clear the relevant district/school pages from memcached (#60).

**Comment by johnnyflowers** [comment]
There is now a cron job on our EC2 server that converts, watermarks, pushes to S3, and updates the live database each night.
